<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="196806" started-at="2021-01-18T19:28:25Z" finished-at="2021-01-18T19:31:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="196806" started-at="2021-01-18T19:28:25Z" finished-at="2021-01-18T19:31:42Z">
      <class name="com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas@657c8ad9]" name="beforeClass" is-config="true" duration-ms="12806" started-at="2021-01-18T13:28:25Z" finished-at="2021-01-18T13:28:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas@657c8ad9]" name="login" duration-ms="7513" started-at="2021-01-18T13:28:38Z" finished-at="2021-01-18T13:28:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="brbEntrar()[pri:0, instance:com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas@657c8ad9]" name="brbEntrar" duration-ms="28056" started-at="2021-01-18T13:28:45Z" finished-at="2021-01-18T13:29:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- brbEntrar -->
        <test-method status="FAIL" signature="verificar()[pri:0, instance:com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas@657c8ad9]" name="verificar" duration-ms="148411" started-at="2021-01-18T13:29:14Z" finished-at="2021-01-18T13:31:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Os dados não concordam com os establecidos expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Os dados não concordam com os establecidos expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas.verificar(ATRCamposAdicionaisOrdemVendas.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificar -->
      </class> <!-- com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
