<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-24T05:39:09Z" name="Default suite" finished-at="2020-11-24T05:40:24Z" duration-ms="75043">
    <groups>
    </groups>
    <test started-at="2020-11-24T05:39:09Z" name="Default test" finished-at="2020-11-24T05:40:24Z" duration-ms="75043">
      <class name="com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe@10f7f7de]" started-at="2020-11-23T23:39:09Z" name="beforeClass" finished-at="2020-11-23T23:39:22Z" duration-ms="12890" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="ingresar()[pri:0, instance:com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe@10f7f7de]" started-at="2020-11-23T23:39:22Z" name="ingresar" finished-at="2020-11-23T23:39:30Z" duration-ms="7967" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ingresar -->
        <test-method signature="mdrEntrar()[pri:0, instance:com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe@10f7f7de]" started-at="2020-11-23T23:39:30Z" name="mdrEntrar" finished-at="2020-11-23T23:39:43Z" duration-ms="13546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mdrEntrar -->
        <test-method signature="detalhe()[pri:0, instance:com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe@10f7f7de]" started-at="2020-11-23T23:39:43Z" name="detalhe" finished-at="2020-11-23T23:40:19Z" duration-ms="36286" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[As informações não são as esperadas expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: As informações não são as esperadas expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe.detalhe(AntecipacaoDetalhe.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- detalhe -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe@10f7f7de]" started-at="2020-11-23T23:40:19Z" name="afterClass" finished-at="2020-11-23T23:40:24Z" duration-ms="4328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.timp.test.MDR.Antecipacao.AntecipacaoDetalhe -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
