<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-10T19:48:44Z" name="Default suite" finished-at="2021-03-10T20:05:15Z" duration-ms="991013">
    <groups>
    </groups>
    <test started-at="2021-03-10T19:48:44Z" name="Default test" finished-at="2021-03-10T20:05:15Z" duration-ms="991013">
      <class name="com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:48:44Z" name="beforeClass" finished-at="2021-03-10T19:50:36Z" duration-ms="112365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="login()[pri:0, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:50:36Z" name="login" finished-at="2021-03-10T19:51:21Z" duration-ms="44214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="brbEntrar()[pri:1, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:51:21Z" name="brbEntrar" finished-at="2021-03-10T19:51:55Z" duration-ms="34494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- brbEntrar -->
        <test-method signature="criarConfiguracaoExecucoes()[pri:2, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:51:55Z" name="criarConfiguracaoExecucoes" finished-at="2021-03-10T19:53:20Z" duration-ms="84723" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- criarConfiguracaoExecucoes -->
        <test-method signature="CriarConfiguracao()[pri:3, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:53:20Z" name="CriarConfiguracao" finished-at="2021-03-10T19:56:43Z" duration-ms="203090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CriarConfiguracao -->
        <test-method signature="configurarConfiguracao()[pri:4, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T19:56:43Z" name="configurarConfiguracao" finished-at="2021-03-10T20:00:42Z" duration-ms="239456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configurarConfiguracao -->
        <test-method signature="executar()[pri:5, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T20:00:42Z" name="executar" finished-at="2021-03-10T20:02:05Z" duration-ms="82304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executar -->
        <test-method signature="EnviarLixeria()[pri:6, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T20:02:05Z" name="EnviarLixeria" finished-at="2021-03-10T20:05:15Z" duration-ms="190339" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Os Subniveis não foram adicinados com sucesso expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Os Subniveis não foram adicinados com sucesso expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP.EnviarLixeria(FatorDeCreditamentoContabilizaçãoDeCIAP.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnviarLixeria -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP@5524cca1]" started-at="2021-03-10T20:05:15Z" name="afterClass" finished-at="2021-03-10T20:05:15Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.timp.test.BCB.ExecucoesSalvas.FatorDeCreditamentoContabilizaçãoDeCIAP.FatorDeCreditamentoContabilizaçãoDeCIAP -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
